-- Baseline schema.
--
-- Table and column definitions are taken verbatim from the DDL Hibernate generates for the
-- entity model (see SchemaDdlGenerator, which emits target/generated-schema.sql without
-- needing a live database). Keeping them identical is what allows
-- spring.jpa.hibernate.ddl-auto=validate to fail fast on entity/schema drift instead of
-- silently mutating production tables the way ddl-auto=update did.
--
-- Indexes and comments below are additive and deliberately not in the generated output.

create table expenses (
    id          bigint generated by default as identity,
    amount      numeric(19, 2),
    created_at  timestamp(6),
    description varchar(255),
    group_id    bigint,
    paid_by     bigint,
    primary key (id)
);

create table expense_shares (
    id           bigint generated by default as identity,
    expense_id   bigint,
    share_amount numeric(19, 2),
    user_id      bigint,
    primary key (id)
);

-- Authoritative write model: one net position per user per group.
-- Storing a net figure rather than a debt graph is what makes cycles (A owes B owes C
-- owes A) cancel automatically instead of needing to be detected and unwound.
create table balances (
    group_id    bigint         not null,
    user_id     bigint         not null,
    net_balance numeric(19, 2) not null,
    primary key (group_id, user_id)
);

-- Consumer-side deduplication ledger. Written in the same transaction as the balance
-- mutations it guards, which is what turns at-least-once delivery into effectively-once
-- processing.
create table processed_events (
    event_id     varchar(255)                not null,
    processed_at timestamp(6) with time zone not null,
    primary key (event_id)
);

-- Transactional outbox: events staged atomically with the state change that produced them.
create table outbox_events (
    id             uuid                        not null,
    aggregate_id   varchar(64)                 not null,
    aggregate_type varchar(64)                 not null,
    attempts       integer                     not null,
    created_at     timestamp(6) with time zone not null,
    event_type     varchar(255)                not null,
    last_error     text,
    message_key    varchar(255),
    payload        text                        not null,
    published_at   timestamp(6) with time zone,
    topic          varchar(255)                not null,
    primary key (id)
);

create table poison_messages (
    id              bigint generated by default as identity,
    error           text,
    failed_at       timestamp(6),
    kafka_offset    bigint,
    kafka_partition integer,
    payload         text,
    topic           varchar(255),
    primary key (id)
);

-- Read models. Derived state only: rebuilt by replaying Kafka, never written by an API.
create table group_balance_view (
    group_id    bigint         not null,
    user_id     bigint         not null,
    net_balance numeric(19, 2) not null,
    primary key (group_id, user_id)
);

create table settlement_view (
    id        bigint generated by default as identity,
    amount    numeric(19, 2) not null,
    from_user bigint,
    group_id  bigint,
    to_user   bigint,
    primary key (id)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- The relay polls exclusively for unpublished rows in creation order. A partial index
-- keeps that scan proportional to the backlog rather than to the full event history, which
-- otherwise grows without bound and makes the poll slower every day the system runs.
create index idx_outbox_unpublished
    on outbox_events (created_at)
    where published_at is null;

create index idx_expense_shares_expense_id on expense_shares (expense_id);
create index idx_expenses_group_id on expenses (group_id);
create index idx_settlement_view_group_id on settlement_view (group_id);
