-- Settle-up: recording that a debt was actually paid.
--
-- Table and column definitions are taken verbatim from SchemaDdlGenerator's output, for the
-- same reason as V1 -- ddl-auto=validate compares them at boot and SchemaValidationIT fails
-- the build if they drift.

-- A payment that happened, as opposed to domain/settlement/Settlement, which is a
-- suggestion the engine computes on demand and never stores.
create table payments (
    id           bigint generated by default as identity,
    amount       numeric(19, 2),
    created_at   timestamp(6),
    from_user_id bigint,
    group_id     bigint,
    note         varchar(255),
    to_user_id   bigint,
    primary key (id)
);

-- Optimistic-lock column for the balance rows.
--
-- Until now expenses were the only writer, and because they are keyed by group they arrived
-- on one partition and were applied by one consumer thread in order, so the plain
-- read-modify-write in BalanceService.applyDelta could not race. Payments arrive on their
-- own topic with their own consumer, so two threads can now reach the same row at once.
-- Without a version the later UPDATE would overwrite a value it never read.
alter table balances
    add column version bigint;

-- Existing rows predate the column. Hibernate needs a concrete version to compare against,
-- so seed them rather than leaving nulls behind.
update balances
set version = 0
where version is null;

create index idx_payments_group_id on payments (group_id, created_at desc);
