-- Identity and the authorization boundary.
--
-- Until now userId and groupId were bare numbers with nothing behind them: any caller could
-- post an expense to any group naming any user, because there was no notion of a caller at
-- all. These three tables are what the membership check is decided against.
--
-- Definitions taken verbatim from SchemaDdlGenerator's output, as in V1 and V2.

create table users (
    id            bigint generated by default as identity,
    created_at    timestamp(6),
    display_name  varchar(255) not null,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    primary key (id)
);

-- "group" is a reserved word in SQL, hence the name; the entity is ExpenseGroup for the
-- same reason.
create table expense_groups (
    id         bigint generated by default as identity,
    created_at timestamp(6),
    created_by bigint       not null,
    name       varchar(255) not null,
    primary key (id)
);

-- The authorization table. Every group-scoped request in the service resolves to a lookup
-- against this one row: present means allowed, absent means 403.
create table group_members (
    group_id  bigint       not null,
    user_id   bigint       not null,
    joined_at timestamp(6) not null,
    primary key (group_id, user_id)
);

-- Referential integrity, which the identifiers never had before. Membership rows are
-- meaningless once their group or user is gone, so they go too.
alter table group_members
    add constraint fk_group_members_group foreign key (group_id) references expense_groups (id) on delete cascade;
alter table group_members
    add constraint fk_group_members_user foreign key (user_id) references users (id) on delete cascade;

alter table expense_groups
    add constraint fk_expense_groups_creator foreign key (created_by) references users (id);

-- "which groups am I in" is on the read path of every authorized request, and the primary
-- key is ordered (group_id, user_id), so it cannot serve a lookup by user alone.
create index idx_group_members_user_id on group_members (user_id);
